---
name: Test Secrets
on:
  pull_request:
    branches:
      - master
      - release/*
jobs:
  test-secrets:
    name: Test Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Test null
        if: secrets.TOKEN == null
        run: echo '`secrets.TOKEN` is null'
      - name: Test String
        if: secrets.TOKEN == ''
        run: echo '`secrets.TOKEN` is an empty string'
